/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.centralmandados.view;

import javax.swing.JInternalFrame;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Laris
 */


public class TelaPrincipalMDI extends javax.swing.JFrame {

    public TelaPrincipalMDI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); 
        setLocationRelativeTo(null);
    }
    
    private void fecharTelasAbertas() {
        for (JInternalFrame frame : painelTelaPrincipal.getAllFrames()) {
            frame.dispose();
        }
    }
   
    public void abrirCentralizado(JInternalFrame janela){
        fecharTelasAbertas();
        
        painelTelaPrincipal.add(janela);
        janela.setVisible(true);
        
        Dimension tamanhoPainel = painelTelaPrincipal.getSize();
        Dimension tamanhoJanela = janela.getSize();
        int x = (tamanhoPainel.width - tamanhoJanela.width)/2;
        int y = (tamanhoPainel.height - tamanhoJanela.height)/2;
        janela.setLocation(x,y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMandados = new javax.swing.JMenu();
        itemCadastrarMandado = new javax.swing.JMenuItem();
        itemAlterarMandado = new javax.swing.JMenuItem();
        itemListarMandados = new javax.swing.JMenuItem();
        menuOficiais = new javax.swing.JMenu();
        itemCadastrarOficial = new javax.swing.JMenuItem();
        itemExcluirOficial = new javax.swing.JMenuItem();
        itemListarOficiais = new javax.swing.JMenuItem();
        menuProcesso = new javax.swing.JMenu();
        itemCadastrarProcesso = new javax.swing.JMenuItem();
        itemListarProcessos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central de Mandados");

        javax.swing.GroupLayout painelTelaPrincipalLayout = new javax.swing.GroupLayout(painelTelaPrincipal);
        painelTelaPrincipal.setLayout(painelTelaPrincipalLayout);
        painelTelaPrincipalLayout.setHorizontalGroup(
            painelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        painelTelaPrincipalLayout.setVerticalGroup(
            painelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuMandados.setForeground(new java.awt.Color(0, 102, 51));
        menuMandados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/centralmandados/images/iconMandados.png"))); // NOI18N
        menuMandados.setText("Mandados");
        menuMandados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        itemCadastrarMandado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemCadastrarMandado.setText("Cadastrar Mandado");
        itemCadastrarMandado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarMandadoActionPerformed(evt);
            }
        });
        menuMandados.add(itemCadastrarMandado);

        itemAlterarMandado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemAlterarMandado.setText("Alterar Mandado");
        itemAlterarMandado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlterarMandadoActionPerformed(evt);
            }
        });
        menuMandados.add(itemAlterarMandado);

        itemListarMandados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemListarMandados.setText("Listar Mandados");
        itemListarMandados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarMandadosActionPerformed(evt);
            }
        });
        menuMandados.add(itemListarMandados);

        jMenuBar1.add(menuMandados);

        menuOficiais.setForeground(new java.awt.Color(0, 102, 51));
        menuOficiais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/centralmandados/images/iconOficiais.png"))); // NOI18N
        menuOficiais.setText("Oficiais");
        menuOficiais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        itemCadastrarOficial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemCadastrarOficial.setText("Cadastrar Oficial");
        itemCadastrarOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarOficialActionPerformed(evt);
            }
        });
        menuOficiais.add(itemCadastrarOficial);

        itemExcluirOficial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemExcluirOficial.setText("Excluir Oficial");
        itemExcluirOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirOficialActionPerformed(evt);
            }
        });
        menuOficiais.add(itemExcluirOficial);

        itemListarOficiais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemListarOficiais.setText("Listar Oficiais");
        itemListarOficiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarOficiaisActionPerformed(evt);
            }
        });
        menuOficiais.add(itemListarOficiais);

        jMenuBar1.add(menuOficiais);

        menuProcesso.setForeground(new java.awt.Color(0, 102, 51));
        menuProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/centralmandados/images/iconProcesso.png"))); // NOI18N
        menuProcesso.setText("Processo");
        menuProcesso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        itemCadastrarProcesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemCadastrarProcesso.setText("Cadastrar Processo");
        itemCadastrarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarProcessoActionPerformed(evt);
            }
        });
        menuProcesso.add(itemCadastrarProcesso);

        itemListarProcessos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemListarProcessos.setText("Listar Processos");
        itemListarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarProcessosActionPerformed(evt);
            }
        });
        menuProcesso.add(itemListarProcessos);

        jMenuBar1.add(menuProcesso);

        menuSistema.setForeground(new java.awt.Color(0, 102, 51));
        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/centralmandados/images/iconSistema.png"))); // NOI18N
        menuSistema.setText("Sistema");
        menuSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSistemaActionPerformed(evt);
            }
        });

        itemSobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuSistema.add(itemSobre);

        itemSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSistema.add(itemSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTelaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTelaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarMandadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarMandadoActionPerformed
        TelaCadastroMandado telaCadMandado = new TelaCadastroMandado();
        abrirCentralizado(telaCadMandado);
    }//GEN-LAST:event_itemCadastrarMandadoActionPerformed

    private void itemListarMandadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarMandadosActionPerformed
        TelaListarMandados telaListMandados = null;
        try {
            telaListMandados = new TelaListarMandados();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipalMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
        abrirCentralizado(telaListMandados);
    }//GEN-LAST:event_itemListarMandadosActionPerformed

    private void itemCadastrarOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarOficialActionPerformed
        TelaCadastroOficial telaCadOficial = new TelaCadastroOficial();
        abrirCentralizado(telaCadOficial);
    }//GEN-LAST:event_itemCadastrarOficialActionPerformed

    private void itemExcluirOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirOficialActionPerformed
        TelaExcluirOficial telaExcOficial = new TelaExcluirOficial();
        abrirCentralizado(telaExcOficial);
    }//GEN-LAST:event_itemExcluirOficialActionPerformed

    private void itemListarOficiaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarOficiaisActionPerformed
        TelaListarOficiais telaListOficiais = new TelaListarOficiais();
        abrirCentralizado(telaListOficiais);
    }//GEN-LAST:event_itemListarOficiaisActionPerformed

    private void menuSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSistemaActionPerformed

    private void itemCadastrarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarProcessoActionPerformed
        TelaCadastroProcesso telaCadProcesso = new TelaCadastroProcesso();
        abrirCentralizado(telaCadProcesso);
    }//GEN-LAST:event_itemCadastrarProcessoActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // Fecha a tela principal
        dispose();

        // Abre a tela de login
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemAlterarMandadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlterarMandadoActionPerformed
        TelaAlterarMandado telaAltMandado = new TelaAlterarMandado();
        abrirCentralizado(telaAltMandado);
    }//GEN-LAST:event_itemAlterarMandadoActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        TelaSobre telaSobre = new TelaSobre();
        abrirCentralizado(telaSobre);
    }//GEN-LAST:event_itemSobreActionPerformed

    private void itemListarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarProcessosActionPerformed
        TelaListarProcessos listaPro = new TelaListarProcessos();
        abrirCentralizado(listaPro);
    }//GEN-LAST:event_itemListarProcessosActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAlterarMandado;
    private javax.swing.JMenuItem itemCadastrarMandado;
    private javax.swing.JMenuItem itemCadastrarOficial;
    private javax.swing.JMenuItem itemCadastrarProcesso;
    private javax.swing.JMenuItem itemExcluirOficial;
    private javax.swing.JMenuItem itemListarMandados;
    private javax.swing.JMenuItem itemListarOficiais;
    private javax.swing.JMenuItem itemListarProcessos;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuMandados;
    private javax.swing.JMenu menuOficiais;
    private javax.swing.JMenu menuProcesso;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JDesktopPane painelTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
