/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.centralmandados.view;

import com.centralmandados.connection.ConnectionFactory;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Laris
 */
public class TelaExcluirOficial extends javax.swing.JInternalFrame {

    public TelaExcluirOficial() {
        initComponents();
        carregarOficiais();
    }
    
    private void carregarOficiais() {
        cmbOficiais.removeAllItems();
        cmbOficiais.addItem("Selecione");

        String sql = "SELECT id, nome FROM oficial ORDER BY nome";
        try (Connection conn = ConnectionFactory.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                cmbOficiais.addItem(rs.getInt("id") + " - " + rs.getString("nome"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao carregar oficiais: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void excluirOficial() {
        String selecionado = (String) cmbOficiais.getSelectedItem();
        if (selecionado == null || selecionado.startsWith("Selecione")) {
            JOptionPane.showMessageDialog(this, "Selecione um oficial.");
            return;
        }

        int id = Integer.parseInt(selecionado.split(" - ")[0]);
        int confirm = JOptionPane.showConfirmDialog(this,
                "Deseja realmente excluir o oficial selecionado?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM oficial WHERE id = ?";
        try (Connection conn = ConnectionFactory.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            int rows = stmt.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Oficial excluído com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Oficial não encontrado ou já excluído.");
            }

        } catch (SQLException e) {
            String msg = e.getMessage().toLowerCase();
            if (msg.contains("foreign key") || msg.contains("constraint")) {
                JOptionPane.showMessageDialog(this,
                    "Não é possível excluir: o oficial está vinculado a um mandado.",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Erro ao excluir oficial: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
            e.printStackTrace();
        }

        carregarOficiais();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExcluirOficial = new javax.swing.JButton();
        btnCancelarCadastro = new javax.swing.JButton();
        cmbOficiais = new javax.swing.JComboBox<>();

        setTitle("Excluir Oficial");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome do Oficial:");

        btnExcluirOficial.setBackground(new java.awt.Color(0, 102, 51));
        btnExcluirOficial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirOficial.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirOficial.setText("Excluir");
        btnExcluirOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirOficialActionPerformed(evt);
            }
        });

        btnCancelarCadastro.setBackground(new java.awt.Color(0, 102, 51));
        btnCancelarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCadastro.setText("Cancelar");
        btnCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroActionPerformed(evt);
            }
        });

        cmbOficiais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cmbOficiais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(btnCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnExcluirOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cmbOficiais, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbOficiais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirOficialActionPerformed
        excluirOficial();
    }//GEN-LAST:event_btnExcluirOficialActionPerformed

    private void btnCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCadastro;
    private javax.swing.JButton btnExcluirOficial;
    private javax.swing.JComboBox<String> cmbOficiais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
